### Get Users

GET http://localhost:3000/users
Content-Type: application/json

### Create Users

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "teste",
    "email": "test@asda.com",
    "password": "123456"
}

### Create Tasks

POST http://localhost:3000/tasks
Content-Type: application/json

{
    "status": "pending",
    "description": "tasks",
    "user_id": "65f7717bc995aa08e96c75da"
}

### Get all Tasks

GET http://localhost:3000/tasks
Content-Type: application/json